### PR TITLE
[Fixes #50] Add gatsby-remark-ample

### LINKED ISSUE #50: Add more structured data for querying
I would like to have a little more control over structuring the data for specific types of content. I've started a PoC with this functionality, and I think it could work.

I would still want to build on top of `gatsby-transformer-remark` because that's doing a lot of work. We can create child nodes of each of the `RemarkMarkdown` nodes, pulling only the necessary attributes with us.

In doing so, we can account for expected fields that may be missing across a particular content type.

All that said, the goals I want to achieve here are:

1. I would like to not have to manage schema in multiple locations (e.g. Forestry config, markdown files, and a schema file). But if there could be a source of truth for content structure, that would be supremely awesome. (i.e. could the node process read the Forestry files?)
2. Avoid builds failing because there are no markdown files and/or because the fields we're looking for in frontmatter aren't actually displayed in any markdown files.

### PR DESCRIPTION
**Pull request by seancdavis**
Swaps gatsby-ample-markdown and gatsby-ample-images in favor of [gatsby-remark-ample](https://github.com/ample/gatsby-remark-ample), which provides structured data queries for local markdown files. It also takes care of the processing that the removed plugins were handling, along with additional support for SEO.

### CODE REVIEW

File: plugins/gatsby-ample-pages/gatsby-node.js [hunk 1]
```diff
@@ -3,43 +3,19 @@ const path = require("path")
 exports.createPages = ({ graphql, actions }) => {
```
Comment (seancdavis) [inline plugins/gatsby-ample-pages/gatsby-node.js:3]: This file is a great example of the benefit gatsby-remark-ample provides us. Look at how much simpler the logic is to building out pages!

File: src/fragments/seo.js [hunk 2]
```diff
@@ -1,20 +1,29 @@
 import { graphql } from "gatsby"
 
 export const SEO = graphql`
-  fragment SEO on MarkdownRemarkFrontmatterSeo {
+  fragment SEO on SeoMeta {
```
Comment (seancdavis) [inline src/fragments/seo.js:4]: This was a recent addition to gatsby-remark-ample in that it creates child nodes for all structured content so that we can have both structured content and still use a fragment.

File: src/pages/index.js [hunk 3]
```diff
@@ -2,27 +2,9 @@ import React from "react"
 import { graphql } from "gatsby"
 import PropTypes from "prop-types"
 
-import { normalizeSEO } from "../helpers"
+import Page from "../templates/page/adapter"
```
Comment (seancdavis) [inline src/pages/index.js:5]: I had realized that it was unnecessary to duplicate all this code and I could simply pass the home page's query result onto the Page template adapter and let it do all the work.
